#loading in the scoring matrix
pam250 = {}
with open("PAM250_here.txt") as f:
    for line in f:
       listy = line.split()
       key = tuple(listy[:2])
       value = int(listy[2])

       pam250[key] = value

#input:two amino acid strings, scoring matrix, and indel penalty
#output: the maximum alignment score of these strings followed by a local alignment achieving this maximum score
def local_align(v, w, score_matrix, penalty_indel):
    #initialize
    s = [[0 for j in range(len(w)+1)] for i in range(len(v)+1)]
    backtrack = [[0 for j in range(len(w)+1)] for i in range(len(v)+1)]

    max_score = -1
    max_i = 0
    max_j = 0
    
    #find max score and fill backtrack to show where local alignment is
    for i in range(1, len(v)+1):
        for j in range(1, len(w)+1):
            try: 
                s[i][j] = max(0, s[i-1][j] - penalty_indel, s[i][j-1] - penalty_indel, s[i-1][j-1] + score_matrix[str(v[i-1]), str(w[j-1])])
                mis_or_match = score_matrix[str(v[i-1]), str(w[j-1])]
            except:
                s[i][j] = max(0, s[i-1][j] - penalty_indel, s[i][j-1] - penalty_indel, s[i-1][j-1] + score_matrix[str(w[j-1]), str(v[i-1])])
                mis_or_match = score_matrix[str(w[j-1]), str(v[i-1])]

            if s[i][j] == s[i-1][j] - penalty_indel:
                backtrack[i][j] = "↓"
            elif s[i][j] == s[i][j-1] - penalty_indel:
                backtrack[i][j] = "→"
            elif s[i][j] == s[i-1][j-1] + mis_or_match:
                backtrack[i][j] = "↘"
            else:
                backtrack[i][j] = "none"

            if s[i][j] > max_score:
                max_score = s[i][j]
                max_i = i
                max_j = j


    #using backtracking matrix find local alignment path
    i = max_i
    j = max_j
    v_final = v[:i]
    w_final = w[:j]
    while backtrack[i][j] != "none" and i != 0 and j != 0:
        if backtrack[i][j] == "↓":
            w_final = w_final[:j] + '-' + w_final[j:]
            i -= 1
        elif backtrack[i][j] == "→":
            v_final = v_final[:i] + '-' + v_final[i:]
            j -= 1
        elif backtrack[i][j] == "↘":
            i -= 1
            j -= 1

    #crop to where local lignment starts
    v_final = v_final[i:]
    w_final = w_final[j:]

    return max_score, v_final, w_final

def main():

    v = 'MEANLY'
    w = 'PENALTY'

    #v = 'AMTAFRYRQGNPRYVKHFAYEIRLSHIWLLTQMPWEFVMGIKMPEDVFQHWRVYSVCTAEPMRSDETYEQKPKPMAKWSGMTIMYQAGIIRQPPRGDRGVSDRNYSQCGKQNQAQLDNNPTWTKYEIEWRVQILPPGAGVFEGDNGQNQCLCPNWAWEQPCQWGALHSNEQYPNRIHLWAPMSKLHIKIEKSSYNRNAQFPNRCMYECEFPSYREQVDSCHYENVQIAFTIFSGAEQKRKFCSCHFWSNFIDQAVFSTGLIPWCYRRDDHSAFFMPNWNKQYKHPQLQFRVAGEGTQCRPFYTREMFTKVSAWRIAGRFAGPYERHHDAHLELWYQHHKVRTGQQLGIIWNNRDKTRNPCPFSAYYNKLPWWKINQNAFYNCLQNIAHSTHDETHEFNPVKCIDWLQGTMVPTECKKGFVHEKCECYRNPGPPLHDMYHQMEDIFGVRFDCLTGWKHLSDYNPCQERRNINDFYIFAYEIAPAVKNLVLSPQPLADATKKCAFNYTPLDQSPVVIACKWYIHQPICMLLIVLICAMDKYNAHMIVIRTTEGQQPMHACRMTEGPGMCMKEPLVTFTLPAQWQWPNHEFKYVYMYVLNYHLSQYTYTDEGHAGGQHYSFNVAVDVGMAWGHNRCYCQPACYSQQETQTRTIDYEKWQYMKHQAFKWGLWFCEQERHAWFKGQNRCEMFTAKMTRMGADSNLDQYKLMLAQNYEEQWEQPIMECGMSEIIEIDPPYRSELIFTFWPFCTYSPWQNLIKCRCNNVIEEMDQCVPLTFIGFGVKQAGGIQAWAFYKEEWTSTYYLMCQCMKSDKAQYPYEIILFWMQPMDTGEQEPPQQNMWIFLPHSWFFDWCCNAPWSEICSSRHDHGQCQDAFYPCELFTVFDDIFTAEPVVCSCFYDDPM'
    # = 'WQEKAVDGTVPSRHQYREKEDRQGNEIGKEFRRGPQVCEYSCNSHSCGWMPIFCIVCMSYVAFYCGLEYPMSRKTAKSQFIEWCDWFCFNHWTNWAPLSIVRTSVAFAVWGHCWYPCGGVCKTNRCKDDFCGRWRKALFAEGPRDWKCCKNDLQNWNPQYSQGTRNTKRMVATTNQTMIEWKQSHIFETWLFCHVIIEYNWSAFWMWMNRNEAFNSIIKSGYPKLLLTQYPLSQGSTPIVKPLIRRDQGKFWAWAQMWWFREPTNIPTADYCHSWWQSRADLQNDRDMGPEADASFYVEFWYWVRCAARTYGQQLGIIWNNRLKTRNPCPYSADGIQNKENYVFWWKNMCTKSHIAFYYCLQNVAHYTHDVTAEFNPVKCIDWLQGHMVLSSWFKYNTECKKLFVHEKCECYRMFCGVVEDIFGVRFHTGWKHLSTAKPVPHVCVYNPSVQERRNINDFYIFYEIAPAVKNLVLSAQPLHDYTKKCAFNYTPITITRIISTRNQIIWAHVVIACQFYSPHQMLLIELAMDKYCADMNVRRSTEGHQPMHACRSTFGPGMAAKEPLVTFTLVAFWQWPNHEFQYVYMYTEDKIIQIGPHLSNGCEMVEYCVDCYAKRPCYRAYSAEAQYWRMITEAEDYSYKTRNAIAATATVRGQYCHPFRWLGIVWMAHHDCFFANECGTICIPQMAEMRPPETTPYEIDIIFMMFWKEHMSTTILDVVGMYRPATFSHWHDAHHQCEPYLTPLMCQSKLVFDAAFTQVGVKGVWYHTEKLELMAGFNHMKFKKEEAQQSCFYWFQDCPDYDPPDAVRKTDEKHIRAHGEIWWLMRYYCMYHILHIASRHEWMHLRWDQACTNPGYELFEFIPWVLRRYVVYDKIRYNYSYRNSASMEFV'

    #v = 'ITIAQGYWIRYCNDGHWMESDNRNMGPYDKNSFWYWDYINPYIGPVWKNLQCRSLHPCYKIQWKVFKEMPPEYTEKITEFCSHKDRHKETVHFLCFTGCAWDKIEDWWVYWLSDGQVSGERDPSLEMMMDWKIVMLRKGTLWIEYAGDQNRGCHRESSLATFMHWNMWFWILHMPHYWYIAAERWVVLSKERAMAQKEWKGCNGDAKCYYHMVAKSYTSSQAYQDIRTGGRRHTDVTINEFDMTVYKGWNCHTLVYKQQVVGRTRYGSMLYPSPQLGYNHHVIFKPQGMWYSGCILHWMEPEWVLPTWFRQIVMRRPGLCLAITCDCAHVRITQGIAAKDTHVHAMTIEEWMTKYPTDPFTRNWVQMQASLDNDDEFLQDESNMPFANEVTIKCWFRVNQGEMCDLLNILCYELLSVCDIVWEWRRSTQWDCENDSQMDAGLQMPPEMLNPEESWYAMFSRNRFYMQWSARHRKDKIVGASQTHMNAEYSFRHWAKDWMCNMHEAFSYWLGRDWIVYGWSKYSDWQIGVFVAECWSMVGCSWVVFMFPEGMSECHCVAPCNHREVPLSKHFWKINKDLNEAFPCPKGICFLGTQAPWMTAQLEVNAAWSSMFGTKTPKCIFCMLGSVLYMNTSRVCIRKTKWYECKWRERLKRPSVDHRHIQRDMWIGYKPTVWVEICINGVHLRKLTEASSDPKDSDDCYPARYAEKDMAYCIRDLFDFRPELPMRCMKESSAGNMWVIVMVWEFNNYRALQSKFCAWQDSGGIHDMLNHMNGPANLYPSFIVRKEGYAVRLPQFHKYFCCCESKVQESTTWDKEDTVEQIRIECKTKHSKAWDHGTFPLRDCCPGSRIQQDLKHGFYEVVMHERYCRYMQMQVWMGYAPVNFGQTHMSGLFARSEGWAKCKYKLIKTEATRSFVYTNPNYTYGWYFYRATPLIGCMPCEDWKNSHEVDNEQGEQKDWQPQRWIWYFFHLVLLYIMHPVFFPSYACMQQGTTWGTCSNVWIMTNWYYSAYARSTIITNWHCRNKHSAYTDWTVIGGRRLEFQNNRLNCDHSTVAWWTTWWDQYTRVNPYNEMGLGEAMCTFCLRKICWGMMYFFHPLYFQRPHAFPRTYQHCGNCTWGNADPVTIHIACNHYHVIWVDDSDCRDHPLQCNESLRWDYMMPFITPTASTRRVDLGAVYSITHISQDHDVPMNIEKFVWWGRMEAWLWGRAMSQCGDILVYCFMAHISDSMIVWGIWLWYCQNNRHRMSYRYGWQPQINVCMHWTILGVLCAKCIGLVRQRQHTWHSGHPSFPCFGCFCQYMQAVLCQKQTGWNFQQYSFLHVEWSGVQSMGPPNGLPNMICMFPLAVAFSQRDSACFSYDGWHQNQNIQDRDVTFIWMMAGIGLPCCREYNKMYVSANRNLVSWASMGGNASSEKIEKFPRAECQGKQTSQTLIASCSWWIWGMKQQEYFKDWCMIRHDEVPAPAGWIRFLFLDHCAREGWGDIQLNAWQSIQFVCFQMARFAWNPPPCPPGCDDMFWRDSRWLYFTCYNKSFHIQVWKIWLVILPIQGETDQVSSFNCHRSMNIMSRKLWRARGSRYTHKCKEQTKATNSPTAAFTPQRVIVDPLICCSGAEKWEKINDHWFCKPYWNPLRQWCLLSSVDCPMTCGGGVEFKDDMVPYHGSEEAVEIRRYLHSKYVVDLVRLQINFIKGCFWWTLRTMHSGHCTMINNCSIDPDYMWQTIMVFVDLQKFMDFEGFVGPDTFACDKKHPLFSTVHQSISCPDVDECCRNRKQKVMHMLKLQNIPSNHYRTNEFATLQGNHYKSRAPHFAMIWMGFYSIIRMCPKPCLSLHMPCYEVLAIEMDRQWVCFHHFEEVCAFIMNLESCCVHWYQEAPNKAHHKPRSWSKDRVVEFDSEWRNVIYKKGRGWEFWRGEAHPCVYNAQHTIEDKTLYQNKPRWSQTRDKRKRNEDNHSSFIMEEHHPAFEVFAKDNLTWYPYHKWAVRCPYLGTKWDEMSSAKPTPPKYHFNYNYYKQGPIDWPASGFHTIIRGAITNFFLVSAFPMNCWSECAECCVMDMWTPAFARTTSHAQICRQNVNEVWGGVIVCTPAHHDESIVVQFWKKNGVPLEDWISAERYESGAAYDVVLSDLGTVPFIQADDNEEEIHDMSFYSQKLLQDMMHSPTFMEQRLFIMGEKVMCTCDPFLSVMYHNDRCSFPHWKPTMMIYSVEHDIRLTCPERKFRHQFGGYIPWTGDLMDGAYVLNVCRYQMMGHPTIPDCQCYWTSPWQPMKSNNGICTRRFSHNLGWLVRPMMNEKDIVWCIQHLKAFPRTSRGFRWDLRQVPVSALVATCPPDYGGWFPQFGKFKCDLKSPKQLCQIEHHQDSNSMPRTFEEPLGHVRSMGYTMPRYWNMAENRAFQRIKNHTFIPCIYVTPAYNQSSCHDDPQSKVCTIDLKEWMPSHTSPTTFCLNPYDVPRSCCNVNKQEVWYNAIPRHIDHWSVEIRKHKENEKATMRGTARFCWHMENSHNWPKLICKFEPKMTWHDWIYAPFGELKVAVEEVEQVSDAVTKFHCCTGSAPSKVPSMDDCLLEYDQISEPSNFACPWVSHDPIDSECQQSAILIDICACMLRVRYEQLGSFFLSKVFNFDSICSDYQGVSIYVYFQFYMGCTIMHEGIITGAHACKCIRRIMKYFTYKNTFEVQVRQHKQANHMHPECIDSQLMCGGQS'
    #w = 'MWNATDKHPNNFMSWSHIKASFCRMYGQQNDGNEQTCHPDTRTMELYWWATKFRQVHHFNCRQTSLTRFLKGINDADFSFIMTHYRYAYAKRWQRLDRSCGCQCDSEMHTLMIRSAHRLKYYDGWQALVMMCWAECPMCGELNSKSVQCCLSIDFGTTPTFMTSRCAPCLTGCSTQNTYHKLKAVDQVSWNIKGQMFFLVWMWLSGWPWTQVAKRMMWPKPPLRLHNRKIHIESHVINVAKIGQCGGGWFSSDSAFIWAMDFPAVQWTHDKEKTSEWSFFWDDIGFYMLAPKGTIFVGMDSWCCFTPFTLRRCWCCLCFHSWQETCKESNERCMSHVFAPEENPLHPNAGYDKNLFVANTGYKGFNYGPKDDTEHANIEENTQIFKGRIKSGHCLVWQAYDGFLYHSTVGLRYVSSGLHWRPPSSTRRCVGAHYHPQEKEYDWWKTFKISDMSTYETQVANVVAVFQNHDFHAETDRDNQIRASSTFDLIHWSEVYESWKFCCWCDIAQNAFENNSFQYSHSGYQMYWGAWHIPCYTVCWCYFFPTCDQPLRNTTKAMLLCMFQMTGPAMSCLITVWETEFWPQHAWDHSIFAEWSIIAIERVRDSFMTQGGHYEHHTMTPDTWMKPTQQESPWYIKETICVMKLNCEYTEKFGVCHEMCYTAECEEQLIVFSANLVAKPNAVWRFADCMDAPKKLRQEKSAYQIYYHDFINGCSCPTTVIRHYIRAVPVMMKVVCFGWLDDPQQGDQSGVNCDCTCRRHRDFAVDTHYNQVGDVAHFANWWKTEYWNRSTSFHKTNSFHTEKIRCRCGCEDIQHRYHLRETPMLAASLITNHFNWQHRMQCWTMPVRREACVRWCICTYCYFENMQEDYFYTTVRDIIYYMVNLFLPVNGMMEVGYACMRTPIYRGMKTFINHGTTWGTSNYSIQIYYSMYARSTIITNWHCHNHSATCYAPPIYGRRLVCMLYHICDHSTVRWWRVAVPMGEAMCTFCLCWNATRIFHPLYFQRTYNHCGNWTEGYPVADPVTIHIACNHYHVIWVDDSDCRDHPLQCNESLENFDRGITPTASTRRFDLGAVYSINGNWALRCCGWIGQDHPVQVKTSLSENIENFVWDPTGRMEAWVSYRAMSQCGDILVYCFMAHRSDLMRVSFFCGSYRYGWQPQINVCMHWTIPSGRPVIGVKFKACAKCIGLVRQRQHTWHNATCGHPSFPRFGCFCDMVAYMALTICPHRIKQTGWNFQYYSFLWLIVEWSGVFRYSMGRVNGLAVAFSWRMHTVLRDAEGLACFSYAGWPCQNILHNTFIWMMAGIGLPCCRYNKMYVSANVVSWASMGQNARVMRGTAEEIEKPRAHFWTSQTAKFGSCIGIAFGSMMHVKCSWWICGDKWQEMNRQAFKDWCMIRDEVPAPFLDHCAFAWLCTNPCKNKPCCMFVYFQFTPFGSNSNPTPCPPDSRWLYFTNKMFIPQVWKIWLVILPIYLMEVSSFMPNKGVSLARGYFWRYKEQTKATPTAQRVIVDPQIHMHCSGHQMEEKWEKINDHWFCKPYWNPLRQWCLLSSVDCPMTYGGDVEFSDDMVPYHGLKYVVDWVRLQSEICTLRTMHKGHCQGNFWVDPQGINNCSINLRPDYAMHLQMIMVFVQLQKFMDFEGFVGPDTFACDKKYPLFSTRHQSISCTDVDPCMRIRKQHVMHMLKWQNIPLQSYNHYRTCCRSWREFATLHYKSRAPHFAMIWMGFYSFIRMCPKPCLSLHMPCYEVLAIEMDRFEETNSFRYGNIMFKELESCCVPNKMIHFDRSWEKDRDTKEFDSKVQWIWWDLVSFQNVIFKKEFWRGEAHSCVYNAQHTIETKTLYQNKPRWSQTRDKRKRNSFIMEEHHPGPEVFAKDNLTYPYHKWAGTKWDCMSSATPTPPPYHFNYNYCNPTNCADNMQGPIDWPASGSMQDMLNHMWASFADTTTSVDLFLIDVSDQKWFHKSYYYLIQFTWPYQIASVKTIDAYAMISRYDVWFIFTGGQEAGWHNFEGEVHYKIWWEMHCHASRDEGDQILWETHCMIVRSDNHCPCMSLIRGKAMAWWKWNGVCVTLRKYVWFGFKQGCAWFDGSNQFDTSCLYRFMFYGHYNLWVRCENGHPICVAHQIIQEQGGWYRVLKEPLLGETCGKYWWKFEQDSRLNVFHDTQAMMWDDPSHTPHYGRHSEMQWMLPPFGKCSPKLFQAQPLDFLISYLTACILPMGICMKIVVIPLMRFWADSFSFTWVYSPYNCWSYWGQWKGAFNCFVDYIPWFSESCKSSIWMQKLDCGQNTNHNCWWDQYGETRRMTSDASSGMKERSSFGERMVMWNHVVSDPVKYVQYNSHRWMERIPIKNFGQMLWKLEIIFKNQVTWCLRWLECTHDKVDFSFMAEFLRLIDSKTAPPECATCKGNTGTKMLWWDTWIEHILDRPFLTAIHLHGLGYFYTNSDVCGVLMVHTYKAWQYPLKDECYWHPLGSILECSRSLDVQMGESYTYSPALHPEVIFNWYLDISLYCCISLQKMAMLFLIISSSWACFNIPKEMKKNTTCHNKIAETWTMYGRNKDVWCEAYFSLPNETLTHGPSIMEGALIWIKQVMEAAMEFHLHTRSGCEHIPFMWAKNWWFHPPMARGGYQIGVLNE'

    score, align_v, align_w = local_align(v, w, pam250, 5)
    print('Score: ', score)
    print(align_v)
    print(align_w)


if __name__ == '__main__':
    main()